### ISSUE TITLE
Nested sequences are not printed as proper string representation in test output

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/testest#2]
First order objected are printed in the test output as their proper string representations (e.g `T{ range f 1 4 1 }`, `{ 1 2 3 }` and `[ 5 3 drop ]`) but nested sequences are not: they're printed as something like `{ ~array~ ~range~ ~quotation~ }`.

**Comment by nomennescio** [comment]
Yes, that's a feature of Factor; to print short presentations of long sequences. In this case that is done by pprint-short in seq. . You can override this with custom printing of messages.

On the other hand, one could argue that by default one would like to see unlimited output. I will therefore change the default to show unlimited output.

**Comment by kazk** [comment]
Deployed #3
