### ISSUE TITLE
LHS is not expected to throw, when RHS throws

### ISSUE THREAD

**Issue by Kacarott** [codewars/testest#33]
According to the docs:

>  If test code on the right side of the arrow -> throws an error, the left side is expected to throw that same error, if it does, the test passes, if it doesn't the test fails.

However this is not the case. When the RHS throws an error, the actual behaviour is that the resulting object is compared against any resulting values from the LHS, regardless of whether the LHS threw or not.

For example, the following word would pass, despite not throwing.

```
: should-throw ( -- msg ) "Error!" ;

<{ should-throw -> "Error!" throw }>
```

I have created a [Kumite](https://www.codewars.com/kumite/62d3d5ac75e9480017c92b4e?sel=62d3d5ac75e9480017c92b4e) providing more in depth examples of where the behaviour is unexpected.

**Comment by nomennescio** [comment]
Fixed in release 2.0.1
