### ISSUE TITLE
Support inexact unit testing

### ISSUE THREAD

**Issue by chunes3** [codewars/testest#4]
Hi there! I have run into an issue where I need to test floating point values for equality, given an epsilon of, say, 1e-15. Is there any way the test vocab could be expanded, maybe with `~>` syntax, to use `(unit-test~)` from `tools.test.private`?

Thanks for your consideration!

**Comment by nomennescio** [comment]
The unit-test~ is hardly every used in the Factor codebase, I only count two files where it is used.
As an alternative, you could use the approach as used in one of these files:

`{ t } [ 4 4 .00000001 ~ ] unit-test`

That would translate into the following Codewars testest framework syntax

`<{   4 4 .00000001 ~ -> t }>`

**Comment by nomennescio** [comment]
The more generic approach would be to have a custom comparator, but it's far from trivial. Need to think about that.

**Comment by chunes3** [comment]
Thanks for the suggestions; it seems there is more flexibility than I thought there was.

**Comment by nomennescio** [comment]
Inexact unit testing is supported by the recently added `math.margins` vocabulary https://github.com/codewars/testest/pull/11.
