### ISSUE TITLE
Preload some vocabs in `extra` to improve runtimes

### ISSUE THREAD

**Issue by nomennescio** [codewars/testest#47]
See https://github.com/codewars/factor/issues/11

As a suggestion, for 0.99, consider preloading some vocabs as mentioned, but final list to be decided

**Comment by nomennescio** [comment]
NOTE: current Factor docs (for 0.100 development version on master branch) only list the following vocabs in extras:
```
assocs.extras
combinators.extras
grouping.extras
math.extras
math.matrices.extras
namespaces.extras
sequences.extras
sets.extras
sorting.extras
splitting.extras
stream.extras
```

Check which vocabs are supported by 0.98, and which are supported by 0.98.

**Comment by nomennescio** [comment]
Factor 0.99 supports the following `extras` vocabs:
```
assocs.extras
combinators.extras
grouping.extras
math.extras
math.matrices.extras
namespaces.extras
sequences.extras
sets.extras
sorting.extras
splitting.extras
stream.extras
```

**Comment by nomennescio** [comment]
Factor 0.98 supports the following `extras` vocabs:
```
assocs.extras
combinators.extras
grouping.extras
math.extras
sequences.extras
sets.extras
sorting.extras
splitting.extras
stream.extras
```

**Comment by nomennescio** [comment]
When looking at the original list as suggested in the issue, some of these are not `extras` vocabs as indicated, but separate vocabs located in the `extra` vocab root. Reconsider the list of vocabs to be preloaded.

**Comment by nomennescio** [comment]
Out of the list of suggested vocabs, the following list is actually in `extra`:
```
coroutines 
decimals
generators
infix
lru-cache
multisets
pair-rocket
pairs
path-finding
qw
trees
variants
```

**Comment by nomennescio** [comment]
Out of the list in the previous comment, the following vocabs are also present in 0.98:
```
decimals
infix
lru-cache
pair-rocket
pairs
path-finding
qw
trees
variants
```

So `coroutines` ,`generators`, and `multisets` were newly introduced in 0.99.

**Comment by Kacarott** [comment]
When I have referred to `extras` I do not mean purely vocabs ending in `.extras`, but rather than vocab in the `extras` root.

Also, all the vocab roots listed have vocabs in `extras`. It is not a list of explicit imports, but rather a list of prefixes to load. See [`load`](https://docs.factorcode.org/content/word-load,vocabs.hierarchy.html).

I have already done extensive testing with compile time, cold load time, warm load time, and image size. The final list is one which includes almost all vocabs which might be useful for kata, with only neglegible size difference (ie. the total size after increased image and removed extras ends up smaller than the current factor docker image).

**Comment by nomennescio** [comment]
> When I have referred to `extras` I do not mean purely vocabs ending in `.extras`, but rather than vocab in the `extras` root.
> 
> Also, all the vocab roots listed have vocabs in `extras`. It is not a list of explicit imports, but rather a list of prefixes to load. See [`load`](https://docs.factorcode.org/content/word-load,vocabs.hierarchy.html).
> 
> I have already done extensive testing with compile time, cold load time, warm load time, and image size. The final list is one which includes almost all vocabs which might be useful for kata, with only neglegible size difference (ie. the total size after increased image and removed extras ends up smaller than the current factor docker image).

Thanks for investigating that.
Right, so you want to load *all* vocabs with these prefixes?
So that would include the ".extras" variants.

Right. If you have already tested that then I'm fine with it. I will make sure it will work for both 0.98 and 0.99.

**Comment by nomennescio** [comment]
I will introduce specializations for versions 0.98 and 0.99, so it will be easy to maintain.

**Comment by Kacarott** [comment]
> So that would include the ".extras" variants.

Yes, but not only those. But the `.extras` are especially important as they are the worst offenders for long load times, `sequences.extras` in particular.

**Comment by nomennescio** [comment]
https://github.com/codewars/testest/commit/2058344ef5875b1ccfe995717849cfd2df2dd0a9
